[platformio]
description = Batterie Plomb-Acide Library Test
src_dir = .

[env:native]
platform = native
build_flags = -std=c99
lib_extra_dirs = .
src_filter = +<examples/basic_usage/>
build_src_filter = +<examples/basic_usage/main.c>